import type { Language } from './types';
import logo from '@/assets/logo.png';

export const ASSETS = {
  logo,
  heroVideo: 'https://framerusercontent.com/assets/nM4DyIHwgOozU0nZZReJ4GVU.mp4',
  heroFallback: 'https://images.unsplash.com/photo-1519337265831-281ec6cc8514?q=80&w=2670&auto=format&fit=crop',
  // Theme colors (oklch). Edit from admin → Theme tab.
  colors: {
    primary: 'oklch(0.72 0.16 230)',
    accent: 'oklch(0.72 0.22 350)',
    secondary: 'oklch(0.86 0.16 90)',
    background: 'oklch(0.985 0.012 230)',
  },
  // Contact info shown in footer / booking
  contact: {
    phone: '+995 555 12 34 56',
    email: 'hello@dubuni.ge',
    address: 'თბილისი, საბურთალო',
  },
  // Admin-blocked time slots: { "2026-05-14": ["11:00", "16:00"] }
  blockedSlots: {} as Record<string, string[]>,
};

export const TRANSLATIONS_VERSION = 2;

export const TRANSLATIONS: Record<Language, any> = {
  ka: {
    ui: {
      book: 'დაჯავშნა',
      premiumCenter: 'პრემიუმ გასართობი ცენტრი',
      heroTitle: 'დუბუნი',
      heroDesc: 'დაუვიწყარი თავგადასავლები, ანიმატორები და საუკეთესო გარემო თქვენი დღესასწაულისთვის.',
      seeAnimators: 'ანიმატორების ნახვა',
      animatorsTitle: 'გმირები',
      animatorsSubtitle: 'გაიცანით ჩვენი',
      animatorsDesc: 'აირჩიეთ თქვენი საყვარელი პერსონაჟები და გარემო თქვენი ღონისძიებისთვის.',
      hostsTitle: 'ანიმატორები',
      hostsSubtitle: 'ჩვენი',
      hostsDesc: 'პროფესიონალი ანიმატორები და წამყვანები თქვენი ივენთისთვის.',
      programsTitle: 'პროგრამები',
      programsSubtitle: 'ასაკის მიხედვით',
      programsDesc: 'ასაკის მიხედვით შერჩეული პროგრამები.',
      services: 'სერვისები',
      servicesSubtitle: 'სპეციალურად თქვენთვის',
      servicesDesc: 'დამატებითი სერვისები რომ თქვენი დღესასწაული უნიკალური გახდეს.',
      menuTitle: 'მენიუ',
      menuDesc: 'ჩვენი რესტორნის სრული ასორტიმენტი თქვენი სადღესასწაულო სუფრისთვის.',
      faq: 'ხშირად დასმული კითხვები',
      back: 'დაბრუნება',
      seeAll: 'იხილეთ ყველა',
      footerDesc: 'სპორტულ-სათავგადასავლო თამაშები და დაუვიწყარი დაბადების დღეები თბილისში.',
      product: 'პროდუქტი',
      company: 'კომპანია',
      copyright: '© 2026 დუბუნი',
      cart: 'კალათა',
      total: 'ჯამი',
      addToCart: 'კალათაში დამატება',
      removeFromCart: 'წაშლა',
      hours: 'საათი',
      quantity: 'რაოდენობა',
      bookNow: 'დაჯავშნა',
      emptyCart: 'კალათა ცარიელია',
      pickDateTime: 'აირჩიეთ თარიღი და დრო',
      pickProgram: 'პროგრამა ასაკის მიხედვით',
      pickAnimators: 'გმირები',
      pickHosts: 'ანიმატორები',
      pickServices: 'სერვისები',
      contactInfo: 'საკონტაქტო ინფორმაცია',
      name: 'სახელი',
      phone: 'ტელეფონი',
      email: 'ელფოსტა',
      comments: 'კომენტარი',
      next: 'შემდეგი',
      finish: 'დასრულება',
      territory: 'ტერიტორია',
      animator: 'ანიმატორი',
      service: 'სერვისი',
      program: 'პროგრამა',
      bookingSuccess: 'მადლობა! თქვენი ჯავშანი მიღებულია, მალე დაგიკავშირდებით.',
      day: 'დღე',
      session: 'სესია',
    },
    nav: [
      { label: 'მთავარი', href: '/' },
      { label: 'გმირები', href: '/animators' },
      { label: 'ანიმატორები', href: '/hosts' },
      { label: 'პროგრამები', href: '/programs' },
      { label: 'სერვისები', href: '/services' },
      { label: 'FAQ', href: '/faq' },
    ],
    animators: [
      { id: 'spider', name: 'ადამიანი ობობა', pricePerHour: 80, maxHours: 4, role: 'გმირი', category: 'სუპერგმირი', image: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1000&auto=format&fit=crop', description: 'აქტიური და ენერგიული პროგრამა.', ageGroup: '6-12' },
      { id: 'batman', name: 'ბეტმენი', pricePerHour: 80, maxHours: 4, role: 'გმირი', category: 'სუპერგმირი', image: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=1000&auto=format&fit=crop', description: 'ღამის რაინდი თქვენს დღესასწაულზე.', ageGroup: '6-12' },
      { id: 'elsa', name: 'ელზა', pricePerHour: 80, maxHours: 3, role: 'გმირი', category: 'პრინცესა', image: 'https://images.unsplash.com/photo-1594465919760-441fe5908ab0?q=80&w=1000&auto=format&fit=crop', description: 'ჯადოსნური და ყინულოვანი თავგადასავალი.', ageGroup: '3-9' },
      { id: 'clown', name: 'მხიარული კლოუნი', pricePerHour: 50, maxHours: 3, role: 'გმირი', category: 'კლასიკური', image: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1000&auto=format&fit=crop', description: 'სიცილი და გართობა გარანტირებულია.', ageGroup: '3-10' },
      { id: 'unicorn', name: 'ცისარტყელა ერთრქა', pricePerHour: 90, maxHours: 3, role: 'გმირი', category: 'ფანტაზია', image: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?q=80&w=1000&auto=format&fit=crop', description: 'ჯადოსნური სამყარო პატარებისთვის.', ageGroup: '3-7' },
      { id: 'pirate', name: 'მეკობრე კაპიტანი', pricePerHour: 70, maxHours: 4, role: 'გმირი', category: 'თავგადასავალი', image: 'https://images.unsplash.com/photo-1609205264511-b755d3a93cc4?q=80&w=1000&auto=format&fit=crop', description: 'საგანძურის ძიების თავგადასავალი.', ageGroup: '6-12' },
    ],
    hosts: [
      { id: 'natia', name: 'ნათია ბ.', pricePerHour: 70, maxHours: 6, role: 'ანიმატორი', category: 'ბავშვები', image: 'https://images.unsplash.com/photo-1559523161-0fc0d8b814a2?q=80&w=1000&auto=format&fit=crop', description: 'პროფესიონალი ბავშვთა პარტიების ანიმატორი.', ageGroup: '3-12' },
      { id: 'giorgi', name: 'გიორგი ს.', pricePerHour: 90, maxHours: 6, role: 'DJ + ანიმატORი', category: 'DJ HOST', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1000&auto=format&fit=crop', description: 'მუსიკა და ანიმაცია ერთად.', ageGroup: 'ყველა' },
      { id: 'marina', name: 'მარინა კ.', pricePerHour: 80, maxHours: 8, role: 'ანიმATORი', category: 'VIP', image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?q=80&w=1000&auto=format&fit=crop', description: 'ელეგანტური ღონისძიებების წამყვანი.', ageGroup: 'ყველა' },
    ],
    programs: [
      { id: 'toddler', name: 'პატარების პROGRAMA', ageRange: '3-5', pricePerHour: 60, maxAnimators: 0, maxHosts: 1, maxHours: 2, category: 'ნაზი', image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=1000&auto=format&fit=crop', description: 'ნაზი, ფერადი აქტივობები ჯადოსნური პერსონაჟებით.' },
      { id: 'kids', name: 'საბავშვო თავგადასავალი', ageRange: '6-9', pricePerHour: 80, maxAnimators: 2, maxHosts: 1, maxHours: 3, category: 'აქტიური', image: 'https://images.unsplash.com/photo-1576442161355-a89de7fd2b7e?q=80&w=1000&auto=format&fit=crop', description: 'აქტიური თამაშები, შეჯიბრებები და სუპერგმირები.' },
      { id: 'teens', name: 'თინეიჯერების ფართი', ageRange: '10+', pricePerHour: 100, maxAnimators: 3, maxHosts: 0, maxHours: 4, category: 'ცეკვა', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1000&auto=format&fit=crop', description: 'თანამედროვე მუსიკა, ქვიზები, დისკოთეკა და სპეცეფექტები.' },
    ],
    timeSlots: [
      { time: '11:00', label: 'დილის სესია', territoryPrice: 200, multiplier: 1.0 },
      { time: '13:30', label: 'შუადღის სესია', territoryPrice: 200, multiplier: 1.0 },
      { time: '16:00', label: 'დღის სესია', territoryPrice: 280, multiplier: 1.1 },
      { time: '18:30', label: 'საღამოს სესია', territoryPrice: 350, multiplier: 1.2 },
      { time: '21:00', label: 'ღამის სესია', territoryPrice: 420, multiplier: 1.35 },
    ],
    services: [
      { id: 'photo', name: 'პროფესიონალი ფოტოგრაფი', price: 80, maxQuantity: 1, maxHours: 4, category: 'მედია', image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=1000&auto=format&fit=crop', description: 'პროფესიონალური ფოტო გადაღება.' },
      { id: 'video', name: 'ვიდეო გადაღება + მონტაჟი', price: 150, maxQuantity: 1, maxHours: 6, category: 'მედია', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1000&auto=format&fit=crop', description: 'პროფესიონალური ვიდეო გადაღება და მონტაჟი.' },
      { id: 'xbox_laser', name: 'XBOX, ლაზერ შოუ, სკანერები', price: 80, maxQuantity: 1, maxHours: 1, category: 'სანახაობა', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1000&auto=format&fit=crop', description: 'ტორტის ჩაქრობის ცერემონია და სპეცეფექტები.' },
      { id: 'animator_ru', name: 'რუსულენოვანი ანიმატორი', price: 150, maxQuantity: 3, maxHours: 4, category: 'ანიმატორი', image: 'https://images.unsplash.com/photo-1607743386760-88f10dca093d?q=80&w=1000&auto=format&fit=crop', description: 'პროფესიონალი ანიმატორი რუსულენოვანი ბავშვებისთვის.' },
      { id: 'animator_en', name: 'ინგლისურენოვანი ანიმატორი', price: 150, maxQuantity: 3, maxHours: 4, category: 'ანიმატორი', image: 'https://images.unsplash.com/photo-1542131015-6c4e58ed4abd?q=80&w=1000&auto=format&fit=crop', description: 'პროფესიონალი ანიმატორი ინგლისურენოვანი ბავშვებისთვის.' },
      { id: 'barman', name: 'ბარმენ შოუ', price: 300, maxQuantity: 1, maxHours: 3, category: 'სანახაობა', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1000&auto=format&fit=crop', description: 'კოქტეილ წვეულება და სანახაობრივი შოუ.' },
    ],
    faq: [
      { question: 'რა არის მინიმალური ასაკი?', answer: 'პროგრამა განკუთვნილია 3+ ასაკის ბავშვებისთვის, ასაკის მიხედვით ფაშინჯად შეგვირჩევია სცენარი.' },
      { question: 'რამდენ ხანს გრძელდება პროგრამა?', answer: 'სტანდარტული ღონისძიება გრძელდება 2 საათი, შესაძლებელია გახანგრძლივება ანიმატორების საათებით.' },
      { question: 'შეგვიძლია საკუთარი საკვების მოტანა?', answer: 'მხოლოდ დაბადების დღის ტორტის და ნამცხვრების მოტანაა ნებადართული.' },
      { question: 'როგორ დავადასტუროთ ჯავშანი?', answer: 'შეავსეთ კალათის გასწვრივ ფორმა და მალე დაგიკავშირდებით ბეს გადახდის ინფორმაციით.' },
      { question: 'როგორ ითვლება ფასი?', answer: 'ფასი ავტომატურად ითვლება: ტერიტორია (დროის მიხედვით) + ანიმატორების საათები × რაოდენობა + არჩეული სერვისები.' },
    ],
    menu: {
      soft: { title: 'გამაგრილებელი', items: [{ name: 'კოკა-კოლა (0.5)', price: '3₾' }, { name: 'ფანტა (0.5)', price: '3₾' }, { name: 'სპრაიტი (0.5)', price: '3₾' }, { name: 'წყალი (0.5)', price: '2₾' }] },
      dough: { title: 'ცომეული', items: [{ name: 'პიცა მარგარიტა', price: '24₾' }, { name: 'პიცა პეპერონი', price: '28₾' }, { name: 'ხაჭაპური იმერული', price: '26₾' }, { name: 'ლობიანი', price: '17₾' }] },
      hot: { title: 'ცხელი სასმელი', items: [{ name: 'ამერიკანო', price: '6₾' }, { name: 'ესპრესო', price: '6₾' }, { name: 'ჩაი', price: '4₾' }] },
      meat: { title: 'სალათები / ხორცეული', items: [{ name: 'კიტრი-პომიდვრის სალათი', price: '17₾' }, { name: 'ღორის მწვადი', price: '24₾' }, { name: 'ქათმის ნაგეთსი', price: '20₾' }] },
      dessert: { title: 'გარნირი / დესერტი', items: [{ name: 'კარტოფილი ფრი', price: '12₾' }, { name: 'ხილის ასორტი', price: '26₾' }] },
    },
  },
  en: {
    ui: {
      book: 'Book Now',
      premiumCenter: 'Premium Entertainment Center',
      heroTitle: 'DUBUNI',
      heroDesc: 'Unforgettable adventures, animators and the best environment for your celebration.',
      seeAnimators: 'See Animators',
      animatorsTitle: 'Animators & Environment',
      animatorsSubtitle: 'Meet Our',
      animatorsDesc: 'Pick your favorite characters and environment for your event.',
      hostsTitle: 'Animators',
      hostsSubtitle: 'Our',
      hostsDesc: 'Professional animators and hosts for your event.',
      programsTitle: 'Programs',
      programsSubtitle: 'By Age Group',
      programsDesc: 'Age-appropriate programs for every child.',
      services: 'Services',
      servicesSubtitle: 'Specially For You',
      servicesDesc: 'Extra services that make your celebration unique.',
      menuTitle: 'Menu',
      menuDesc: 'Full menu of our restaurant for your festive table.',
      faq: 'FAQ',
      back: 'Back',
      seeAll: 'See All',
      footerDesc: 'Sports & adventure games and unforgettable birthdays in Tbilisi.',
      product: 'Product',
      company: 'Company',
      copyright: '© 2026 DUBUNI',
      cart: 'Cart',
      total: 'Total',
      addToCart: 'Add to cart',
      removeFromCart: 'Remove',
      hours: 'Hours',
      quantity: 'Qty',
      bookNow: 'Book Now',
      emptyCart: 'Your cart is empty',
      pickDateTime: 'Pick date & session',
      pickProgram: 'Program by age',
      pickAnimators: 'Animators & Environment',
      pickHosts: 'Animators',
      pickServices: 'Services',
      contactInfo: 'Contact information',
      name: 'Name',
      phone: 'Phone',
      email: 'Email',
      comments: 'Comments',
      next: 'Next',
      finish: 'Finish',
      territory: 'Territory',
      animator: 'Animator',
      service: 'Service',
      program: 'Program',
      bookingSuccess: 'Thank you! Your booking has been received, we will contact you shortly.',
      day: 'Day',
      session: 'Session',
    },
    nav: [
      { label: 'Home', href: '/' },
      { label: 'Heroes', href: '/animators' },
      { label: 'Animators', href: '/hosts' },
      { label: 'Programs', href: '/programs' },
      { label: 'Services', href: '/services' },
      { label: 'FAQ', href: '/faq' },
    ],
    animators: [
      { id: 'spider', name: 'Spider-Man', pricePerHour: 80, maxHours: 4, role: 'Character', category: 'Superhero', image: 'https://images.unsplash.com/photo-1635805737707-575885ab0820?q=80&w=1000&auto=format&fit=crop', description: 'Active and energetic program.', ageGroup: '6-12' },
      { id: 'batman', name: 'Batman', pricePerHour: 80, maxHours: 4, role: 'Character', category: 'Superhero', image: 'https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=1000&auto=format&fit=crop', description: 'Dark Knight at your celebration.', ageGroup: '6-12' },
      { id: 'elsa', name: 'Elsa', pricePerHour: 80, maxHours: 3, role: 'Character', category: 'Princess', image: 'https://images.unsplash.com/photo-1594465919760-441fe5908ab0?q=80&w=1000&auto=format&fit=crop', description: 'Magical and icy adventure.', ageGroup: '3-9' },
      { id: 'clown', name: 'Fun Clown', pricePerHour: 50, maxHours: 3, role: 'Character', category: 'Classic', image: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1000&auto=format&fit=crop', description: 'Laughter and fun guaranteed.', ageGroup: '3-10' },
      { id: 'unicorn', name: 'Rainbow Unicorn', pricePerHour: 90, maxHours: 3, role: 'Character', category: 'Fantasy', image: 'https://images.unsplash.com/photo-1599842057874-37393e9342df?q=80&w=1000&auto=format&fit=crop', description: 'Magical world for the little ones.', ageGroup: '3-7' },
      { id: 'pirate', name: 'Pirate Captain', pricePerHour: 70, maxHours: 4, role: 'Character', category: 'Adventure', image: 'https://images.unsplash.com/photo-1609205264511-b755d3a93cc4?q=80&w=1000&auto=format&fit=crop', description: 'Treasure hunt adventure.', ageGroup: '6-12' },
    ],
    hosts: [
      { id: 'natia', name: 'Natia B.', pricePerHour: 70, maxHours: 6, role: 'Animator', category: 'Kids', image: 'https://images.unsplash.com/photo-1559523161-0fc0d8b814a2?q=80&w=1000&auto=format&fit=crop', description: 'Professional kids party animator.', ageGroup: '3-12' },
      { id: 'giorgi', name: 'Giorgi S.', pricePerHour: 90, maxHours: 6, role: 'DJ + Animator', category: 'DJ HOST', image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1000&auto=format&fit=crop', description: 'Music and animation combined.', ageGroup: 'All ages' },
      { id: 'marina', name: 'Marina K.', pricePerHour: 80, maxHours: 8, role: 'Animator', category: 'VIP', image: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?q=80&w=1000&auto=format&fit=crop', description: 'Elegant event host.', ageGroup: 'All ages' },
    ],
    programs: [
      { id: 'toddler', name: 'Toddler Program', ageRange: '3-5', pricePerHour: 60, maxAnimators: 0, maxHosts: 1, maxHours: 2, category: 'Gentle', image: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?q=80&w=1000&auto=format&fit=crop', description: 'Gentle, colorful activities with magical characters.' },
      { id: 'kids', name: 'Kids Adventure', ageRange: '6-9', pricePerHour: 80, maxAnimators: 2, maxHosts: 1, maxHours: 3, category: 'Active', image: 'https://images.unsplash.com/photo-1576442161355-a89de7fd2b7e?q=80&w=1000&auto=format&fit=crop', description: 'Active games, competitions and superheroes.' },
      { id: 'teens', name: 'Teen Party', ageRange: '10+', pricePerHour: 100, maxAnimators: 3, maxHosts: 0, maxHours: 4, category: 'Dance', image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1000&auto=format&fit=crop', description: 'Modern music, quizzes, disco and special effects.' },
    ],
    timeSlots: [
      { time: '11:00', label: 'Morning', territoryPrice: 200, multiplier: 1.0 },
      { time: '13:30', label: 'Afternoon', territoryPrice: 200, multiplier: 1.0 },
      { time: '16:00', label: 'Day', territoryPrice: 280, multiplier: 1.1 },
      { time: '18:30', label: 'Evening', territoryPrice: 350, multiplier: 1.2 },
      { time: '21:00', label: 'Night', territoryPrice: 420, multiplier: 1.35 },
    ],
    services: [
      { id: 'photo', name: 'Photographer', price: 80, maxQuantity: 1, maxHours: 4, category: 'Media', image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=1000&auto=format&fit=crop', description: 'Professional photo session.' },
      { id: 'video', name: 'Video Production', price: 150, maxQuantity: 1, maxHours: 6, category: 'Media', image: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1000&auto=format&fit=crop', description: 'Professional video shooting and editing.' },
      { id: 'xbox_laser', name: 'XBOX, Laser Show', price: 80, maxQuantity: 1, maxHours: 1, category: 'Show', image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1000&auto=format&fit=crop', description: 'Cake ceremony special effects.' },
      { id: 'animator_ru', name: 'Russian Animator', price: 150, maxQuantity: 3, maxHours: 4, category: 'Animator', image: 'https://images.unsplash.com/photo-1607743386760-88f10dca093d?q=80&w=1000&auto=format&fit=crop', description: 'Professional animator for Russian-speaking kids.' },
      { id: 'animator_en', name: 'English Animator', price: 150, maxQuantity: 3, maxHours: 4, category: 'Animator', image: 'https://images.unsplash.com/photo-1542131015-6c4e58ed4abd?q=80&w=1000&auto=format&fit=crop', description: 'Professional animator for English-speaking kids.' },
      { id: 'barman', name: 'Barman Show', price: 300, maxQuantity: 1, maxHours: 3, category: 'Show', image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?q=80&w=1000&auto=format&fit=crop', description: 'Cocktail party and spectacular barman show.' },
    ],
    faq: [
      { question: 'What is the minimum age?', answer: 'Programs are designed for ages 3+, scenarios adapt by age group.' },
      { question: 'How long does the program last?', answer: 'Standard event lasts 2 hours; extensible via animator hours.' },
      { question: 'Can we bring our own food?', answer: 'Only birthday cakes and pastries are allowed.' },
      { question: 'How do we confirm a booking?', answer: 'Fill out the form next to the cart — we will contact you with deposit details.' },
      { question: 'How is the price calculated?', answer: 'Auto-calculated: territory (by time) + animator hours × quantity + selected services.' },
    ],
    menu: {
      soft: { title: 'Soft Drinks', items: [{ name: 'Coca-Cola (0.5)', price: '3₾' }, { name: 'Fanta (0.5)', price: '3₾' }, { name: 'Water (0.5)', price: '2₾' }] },
      dough: { title: 'Baked', items: [{ name: 'Pizza Margherita', price: '24₾' }, { name: 'Pizza Pepperoni', price: '28₾' }, { name: 'Khachapuri Imeruli', price: '26₾' }] },
      hot: { title: 'Coffee / Tea', items: [{ name: 'Americano', price: '6₾' }, { name: 'Espresso', price: '6₾' }, { name: 'Tea', price: '4₾' }] },
      meat: { title: 'Salads / Meat', items: [{ name: 'Tomato-Cucumber Salad', price: '17₾' }, { name: 'Pork Skewers', price: '24₾' }, { name: 'Chicken Nuggets', price: '20₾' }] },
      dessert: { title: 'Sides / Dessert', items: [{ name: 'French Fries', price: '12₾' }, { name: 'Fruit Plate', price: '26₾' }] },
    },
  },
};
