/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnimatorsRouteImport } from './routes/animators'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as HostsIndexRouteImport } from './routes/hosts.index'
import { Route as AnimatorsIndexRouteImport } from './routes/animators.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as ProgramsProgramIdRouteImport } from './routes/programs.$programId'
import { Route as HostsHostIdRouteImport } from './routes/hosts.$hostId'
import { Route as AnimatorsAnimatorIdRouteImport } from './routes/animators.$animatorId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimatorsRoute = AnimatorsRouteImport.update({
  id: '/animators',
  path: '/animators',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsRoute,
} as any)
const HostsIndexRoute = HostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostsRoute,
} as any)
const AnimatorsIndexRoute = AnimatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimatorsRoute,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)
const ProgramsProgramIdRoute = ProgramsProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => ProgramsRoute,
} as any)
const HostsHostIdRoute = HostsHostIdRouteImport.update({
  id: '/$hostId',
  path: '/$hostId',
  getParentRoute: () => HostsRoute,
} as any)
const AnimatorsAnimatorIdRoute = AnimatorsAnimatorIdRouteImport.update({
  id: '/$animatorId',
  path: '/$animatorId',
  getParentRoute: () => AnimatorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/animators': typeof AnimatorsRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/faq': typeof FaqRoute
  '/hosts': typeof HostsRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/animators/$animatorId': typeof AnimatorsAnimatorIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/animators/': typeof AnimatorsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/faq': typeof FaqRoute
  '/animators/$animatorId': typeof AnimatorsAnimatorIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/animators': typeof AnimatorsIndexRoute
  '/hosts': typeof HostsIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/animators': typeof AnimatorsRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/faq': typeof FaqRoute
  '/hosts': typeof HostsRouteWithChildren
  '/programs': typeof ProgramsRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/animators/$animatorId': typeof AnimatorsAnimatorIdRoute
  '/hosts/$hostId': typeof HostsHostIdRoute
  '/programs/$programId': typeof ProgramsProgramIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/animators/': typeof AnimatorsIndexRoute
  '/hosts/': typeof HostsIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/animators'
    | '/auth'
    | '/booking'
    | '/faq'
    | '/hosts'
    | '/programs'
    | '/services'
    | '/animators/$animatorId'
    | '/hosts/$hostId'
    | '/programs/$programId'
    | '/services/$serviceId'
    | '/animators/'
    | '/hosts/'
    | '/programs/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/booking'
    | '/faq'
    | '/animators/$animatorId'
    | '/hosts/$hostId'
    | '/programs/$programId'
    | '/services/$serviceId'
    | '/animators'
    | '/hosts'
    | '/programs'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/animators'
    | '/auth'
    | '/booking'
    | '/faq'
    | '/hosts'
    | '/programs'
    | '/services'
    | '/animators/$animatorId'
    | '/hosts/$hostId'
    | '/programs/$programId'
    | '/services/$serviceId'
    | '/animators/'
    | '/hosts/'
    | '/programs/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AnimatorsRoute: typeof AnimatorsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  FaqRoute: typeof FaqRoute
  HostsRoute: typeof HostsRouteWithChildren
  ProgramsRoute: typeof ProgramsRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animators': {
      id: '/animators'
      path: '/animators'
      fullPath: '/animators'
      preLoaderRoute: typeof AnimatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/programs/': {
      id: '/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/hosts/': {
      id: '/hosts/'
      path: '/'
      fullPath: '/hosts/'
      preLoaderRoute: typeof HostsIndexRouteImport
      parentRoute: typeof HostsRoute
    }
    '/animators/': {
      id: '/animators/'
      path: '/'
      fullPath: '/animators/'
      preLoaderRoute: typeof AnimatorsIndexRouteImport
      parentRoute: typeof AnimatorsRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/programs/$programId': {
      id: '/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof ProgramsProgramIdRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/hosts/$hostId': {
      id: '/hosts/$hostId'
      path: '/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof HostsHostIdRouteImport
      parentRoute: typeof HostsRoute
    }
    '/animators/$animatorId': {
      id: '/animators/$animatorId'
      path: '/$animatorId'
      fullPath: '/animators/$animatorId'
      preLoaderRoute: typeof AnimatorsAnimatorIdRouteImport
      parentRoute: typeof AnimatorsRoute
    }
  }
}

interface AnimatorsRouteChildren {
  AnimatorsAnimatorIdRoute: typeof AnimatorsAnimatorIdRoute
  AnimatorsIndexRoute: typeof AnimatorsIndexRoute
}

const AnimatorsRouteChildren: AnimatorsRouteChildren = {
  AnimatorsAnimatorIdRoute: AnimatorsAnimatorIdRoute,
  AnimatorsIndexRoute: AnimatorsIndexRoute,
}

const AnimatorsRouteWithChildren = AnimatorsRoute._addFileChildren(
  AnimatorsRouteChildren,
)

interface HostsRouteChildren {
  HostsHostIdRoute: typeof HostsHostIdRoute
  HostsIndexRoute: typeof HostsIndexRoute
}

const HostsRouteChildren: HostsRouteChildren = {
  HostsHostIdRoute: HostsHostIdRoute,
  HostsIndexRoute: HostsIndexRoute,
}

const HostsRouteWithChildren = HostsRoute._addFileChildren(HostsRouteChildren)

interface ProgramsRouteChildren {
  ProgramsProgramIdRoute: typeof ProgramsProgramIdRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsProgramIdRoute: ProgramsProgramIdRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AnimatorsRoute: AnimatorsRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  FaqRoute: FaqRoute,
  HostsRoute: HostsRouteWithChildren,
  ProgramsRoute: ProgramsRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
